name: ci with unit tests

on:
  push:
    branches: [master]

jobs:
  customerservicetests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [25]

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: customerservice

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/customerservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    steps:
      - name: Checka ut customerservice
        uses: actions/checkout@v4

      - name: Sätt upp java matrix
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          cache: "maven"

      - name: build with maven
        run: mvn --batch-mode test